version: '3.1'
services:
  database:
    image: 'postgres:11.1-alpine'
    container_name: database
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - '47001:5432'

  nginx:
    image: 'nginx:alpine'
    container_name: nginx
    working_dir: /application
    volumes:
      - '.:/application'
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '47000:80'
      - "1023:22"
    depends_on:
      - database
    links:
      - php-fpm

  php-fpm:
    image: fpm
    build: '.'
    container_name: fpm
    working_dir: /application
    volumes:
      - '.:/application'
